config/routes.rb
Rails.application.routes.draw do
  root "application#home"

  get "login" => "user_sessions#new", as: :login
  get "logout" => "user_sessions#destroy", as: :logout

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :show, :new, :create, :destroy]
  resources :guests, only: [:create, :edit, :update]
  resources :shots, only: [:index, :new, :create, :destroy]
  resources :tags, only: [:index]
  resource :pin, only: [:create, :destroy]
  resource :profile, only: :show
end

app/models/shot.rb
require 'digest/md5'

class Shot < ActiveRecord::Base
  belongs_to :user
  has_many :taggables, dependent: :destroy
  has_many :tags, through: :taggables
  has_many :pins

  validates :url, presence: true
  validates :tag_list, presence: true

  attr_accessor :tag_list
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  def fetch_screenshot
    # TODO FetchScreenshotJob.perform_later(url)

    screenshots_dir = File.join(Rails.root, "public", "screenshots")
    filename = File.join(screenshots_dir, "#{md5}.png")

    unless File.exist?(filename)
      Dir.chdir(screenshots_dir) do
        system("pageres #{url} --filename='#{md5}'")
      end
    end
  end

  def crop_screenshot
    # TODO
    path = "/shots/#{SecureRandom.hex(24)}.png"
    screenshots_dir = File.join(Rails.root, "public", "screenshots")
    filename = File.join(screenshots_dir, "#{md5}.png")

    img = MiniMagick::Image.open(filename)
    img.crop "#{crop_w}x#{crop_h}+#{crop_x}+#{crop_y}"
    img.format 'png'
    img.write File.join(Rails.root, "public", path)

    path
  end

  def screenshot_url
    "/screenshots/#{md5}.png"
  end

  def md5
    Digest::MD5.hexdigest(url)
  end
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  skip_before_filter :require_login, only: [:index]

  def index
    if params[:tag]
      @shots = Tag.find_by(name: params[:tag]).shots.shuffle
    else
      @shots = Shot.all.shuffle
    end
    @tags = Tag.all.includes(:shots)
  end

  def new
    name = Base64.decode64(params[:title])
    url = Base64.decode64(params[:exturl])

    @shot = Shot.new(name: name, url: url)
    @shot.fetch_screenshot
  end

  def create
    @shot = Shot.new(shot_params)
    @shot.user = current_user
    @shot.image = @shot.crop_screenshot

    if @shot.save
      @shot.tag_list.split(',').each do |name|
        @shot.tags << Tag.find_or_create_by(name: name)
      end

      redirect_to profile_path, notice: "Your shot has been saved!"
    else
      render :new
    end
  end

  def destroy
    @shot = Shot.find(params[:id])
    if @shot.user == current_user
      @shot.destroy
      # TODO Amazon.bucket.find(@shot.image).destroy
      redirect_to profile_path
    else
      not_authorized
    end
  end

  private

  def shot_params
    params.require(:shot).permit(:name, :url, :crop_x, :crop_y, :crop_w, :crop_h, :filename, :tag_list)
  end
end

app/views/shots/_pins.slim
- if logged_in? && current_user.not_saved_shot?(shot)
  - if current_user.pinned_shot?(shot)
    = link_to 'Unpin', pin_path(shot_id: shot.id, user_id: current_user.id), method: :delete, class: 'btn btn-unpin'
  - else
    = link_to 'Pin', pin_path(shot_id: shot.id, user_id: current_user.id), method: :create, class: 'btn btn-pin'

app/views/shots/_tags.slim
small class="text-muted"
  | #{shot.tags.join(', ')}

app/views/shots/index.slim
div class="grid"
  div class="grid-item 1/6"
    p class="text-muted text-center"
      - if params[:tag]
        | Selected: <strong>#{params[:tag]}</strong>
    ul class="list-menu"
      li= link_to "All", shots_path
      - @tags.each do |tag|
        - if tag.shots.size > 0
          li= link_to "#{tag} (#{tag.shots.size})", shots_path(tag: tag.name)
  div class="grid-item 5/6"
    - @shots.each do |shot|
      div class="shot"
        img src=shot.image class="img-responsive"
        div class="grid grid-middle grid-pair margin-quarter-top"
          div class="grid-item 1/6"
            = render 'pins', shot: shot
          div class="grid-item 5/6"
            = render 'tags', shot: shot
            - unless current_user && current_user == shot.user
              small class="text-muted"
                |  | by #{link_to shot.user, user_path(shot.user)}

app/views/shots/new.slim
- content_for :no_navbar, true

p
  | Crop element from the screenshot that is interesting for you, add tags and save the shot:<br>

div class="grid grid-center"
  div class="grid-item 3/5"
    div class="img-loader js-img-loader js-cropper" data-tmp=@shot.screenshot_url
  div class="grid-item 2/5"
    = form_for @shot, html: { class: "form-stacked margin-base-bottom" } do |f|
      - if @shot.errors.any?
        #error_explanation class="box box-negative margin-base-bottom"
          p= "#{pluralize(@shot.errors.count, "error")} prohibited this shot from being saved:"
          ul
            - @shot.errors.full_messages.each do |message|
              li = message

      = f.label :tag_list, "Tags"
      = f.text_field :tag_list, class: "js-tags"
      small class="text-muted"
        | To add a new tag just type it and press ',' or 'enter'

      = f.hidden_field :name
      = f.hidden_field :url

      - %w(x y w h).each do |attr|
        = f.hidden_field "crop_#{attr}", class: "js-crop-#{attr}"

      div class="margin-base-top"
        = f.submit "Save this shot for me!"