config/routes.rb
Rails.application.routes.draw do
  root "application#home"

  get "login" => "user_sessions#new", as: :login
  get "logout" => "user_sessions#destroy", as: :logout

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :show, :new, :create, :destroy]
  resources :guests, only: [:create, :edit, :update]
  resources :shots, only: [:index, :new, :create, :destroy]
  resources :tags, only: [:index]
  resource :pin, only: [:create, :destroy]
  resource :profile, only: :show
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :shots, dependent: :destroy
  has_many :tags, through: :shots
  has_many :pins
  has_many :pinned_shots, through: :pins, source: :shot
  has_many :pinned_tags, through: :pinned_shots, source: :tags

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  validates :email, presence: true, uniqueness: true, format: /@/
  validates :username, presence: true, uniqueness: true

  def shots_and_pinned_shots
    shots + pinned_shots
  end

  def tags_and_pinned_tags
    tags + pinned_tags
  end

  def not_saved_shot?(shot)
    !shots.include?(shot)
  end

  def pinned_shot?(shot)
    pinned_shots.include?(shot)
  end

  def to_s
    username
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:new, :show, :create]

  def new
    @user = User.new
  end

  def show
    @user = User.includes(:shots, :pinned_shots).find(params[:id])
    if params[:tag]
      @shots = @user.shots_and_pinned_shots.find_all do |shot|
        shot.tags.map(&:name).include?(params[:tag])
      end
    else
      @shots = @user.shots_and_pinned_shots
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      @user.remember_me!
      redirect_to profile_path, notice: 'Account created!'
    else
      render :new
    end
  end

  def destroy
    authorize(params[:id])
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: 'Account removed.'
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/views/users/new.slim
h2 class="text-muted text-center margin-double-bottom"
  | Sign up

div class="grid grid-center"
  div class="grid-item 1/3"
    = form_for @user, html: { class: 'form-stacked margin-base-bottom' } do |f|
      - if @user.errors.any?
        #error_explanation class="box box-negative margin-base-bottom"
          p= "#{pluralize(@user.errors.count, "error")} prohibited:"
          ul
            - @user.errors.full_messages.each do |message|
              li = message

      = f.label :username
      = f.text_field :username, class: '1/1'

      = f.label :email, 'E-mail'
      = f.text_field :email, class: '1/1'

      = f.label :password
      = f.password_field :password, class: '1/1'

      = f.label :password_confirmation, 'Repeat password'
      = f.password_field :password_confirmation, class: '1/1'

      div class="text-center"
        = f.submit 'Sign up now'

    ul class="list-reset"
      li= link_to "Already have an account? Log in.", login_path
      li= link_to "Start now without an account.", guests_path, method: :post

app/views/users/show.slim
h2 class="text-muted text-center margin-double-bottom"
  | #{@user} shots
- if @user.shots.empty?
  div class="box box-informative"
    | This user doesn't have any shots
- else
  div class="grid"
    div class="grid-item 1/6"
      p class="text-muted text-center"
        - if params[:tag]
          | Selected: <strong>#{params[:tag]}</strong>
      ul class="list-menu"
        li= link_to "All", user_path(@user)
        - @user.tags_and_pinned_tags.group_by(&:name).each do |tag, group|
          li
            = link_to "#{tag} (#{group.size})", user_path(@user, tag: tag)
    div class="grid-item 5/6"
      - @shots.each do |shot|
        div class="shot"
          img src=shot.image class="img-responsive"
          div class="grid grid-middle grid-pair margin-quarter-top"
            div class="grid-item 1/6"
              = render 'shots/pins', shot: shot
            div class="grid-item 5/6"
              = render 'shots/tags', shot: shot