config/routes.rb
Rails.application.routes.draw do
  root "application#home"

  get "login" => "user_sessions#new", as: :login
  get "logout" => "user_sessions#destroy", as: :logout

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :show, :new, :create, :destroy]
  resources :guests, only: [:create, :edit, :update]
  resources :shots, only: [:index, :new, :create, :destroy]
  resources :tags, only: [:index]
  resource :pin, only: [:create, :destroy]
  resource :profile, only: :show
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :require_login
  skip_before_filter :require_login, only: [:home]

  def home
  end

  protected

  def authorize(user_id)
    not_authorized unless user_id.to_i == current_user.id
  end

  private

  def not_authorized
    redirect_back_or_to root_path, alert: "You don't have that access"
  end

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def guest_expires_at_in_words(user)
    distance_of_time_in_words(Time.now,
                              user.remember_me_token_expires_at)
  end

  def bookmarklet
    redirect = new_shot_url(protocol: 'http')
    exturl = "window.btoa(location.href)"
    title = "window.btoa(window.document.title)"
    %(javascript:(function(){window.open('#{redirect}?exturl='+#{exturl}+'&title='+#{title});})();)
  end
end

app/views/application/_flash.slim
- if flash[:notice]
  div class="box box-informative margin-base-bottom"
    = flash[:notice]

- if flash[:alert]
  div class="box box-negative margin-base-bottom"
    = flash[:alert]

app/views/application/_footer.slim
div class="sticky-footer"
  div class="footer"
    div class="container"
      p class="no-margin-bottom text-center"
        | This application was created in 48h for the
          #{link_to "Rails Rumble", "http://railsrumble.com/entries/180-uishots"}
          hackathon by #{link_to "Bartłomiej Kozal", "http://bkzl.github.io"}.
          <br>Cookies are used to store sessions.

app/views/application/_how_it_works.slim
h3 class="text-center" How it works?

ol
  li Drag our #{link_to "UIshots", bookmarklet, class: 'bookmarklet'} bookmarklet to your bookmarks bar.
  li Now when you notice interesting UI element on any web page click on the bookmarklet!
  li Crop part of a screenshot, add tags and save the new shot. It will be available for everyone on UIshots!
  li It's not everything! You can explore and pin shots made by other users!

app/views/application/_navbar.slim
div class="navbar"
  div class="container navbar-container"
    div class="grid grid-pair"
      div class="grid-item 1/4"
        ul class="list-inline"
          li= link_to "UIshots", (logged_in? ? shots_path : root_path), class: "brand-navbar"
          li class="text-muted text-small text-uppercase" Beta
      div class="grid-item 3/4"
        ul class="navbar-menu"
          li= link_to "Explore", shots_path
          - if current_user
            li= link_to "Your Shots", profile_path
            - if current_user.guest?
              li= link_to "Become a member", edit_guest_path(current_user)
            - else
              li= link_to "Logout", logout_path
          - else
            li= link_to "Login", login_path
            li= link_to "Sign up", new_user_path

div class="container text-right text-small text-muted margin-base-bottom"
  - if current_user
    ' Logged in as <strong>#{current_user}</strong>.
    - if current_user.guest?
      | Your account <strong>will expire in
        #{guest_expires_at_in_words(current_user)}</strong>.

app/views/application/home.slim
div class="margin-double-top"
  div class="box box-informative text-center"
    | This application was created in 48h for the
      #{link_to "Rails Rumble", "http://railsrumble.com/entries/180-uishots"}
      hackathon by #{link_to "Bartłomiej Kozal", "http://bkzl.github.io"}.

div class="grid text-center"
  div class="grid-item 1/1"
    h1 class="brand-heading margin-base-bottom"
      | Save UI/UX elements found on the Internet

    ul class="list-inline"
      li= link_to "Start now without an account", guests_path, method: :post, class: "btn brand-btn"

hr class="margin-triple-ends"

div class="grid grid-center text-center"
  div class="grid-item 2/5"
    = image_tag 'save.png'
    h2 class="brand-subheading"
      | Save and share favorite<br> UI elements found on the Internet
  div class="grid-item 1/10"
  div class="grid-item 2/5"
    = image_tag 'explore.png'
    h2 class="brand-subheading"
      | Explore huge UI library,<br> get inspired and pin existing shots

hr class="margin-triple-ends"

= render "how_it_works"