config/routes.rb
Rails.application.routes.draw do
  root "application#home"

  get "login" => "user_sessions#new", as: :login
  get "logout" => "user_sessions#destroy", as: :logout

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :show, :new, :create, :destroy]
  resources :guests, only: [:create, :edit, :update]
  resources :shots, only: [:index, :new, :create, :destroy]
  resources :tags, only: [:index]
  resource :pin, only: [:create, :destroy]
  resource :profile, only: :show
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:username], params[:password], params[:remember])
      redirect_back_or_to(profile_path, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/views/user_sessions/new.slim
h2 class="text-muted text-center margin-double-bottom"
  | Login

div class="grid grid-center"
  div class="grid-item 1/3"
    = form_tag user_sessions_path, method: :post, class: "form-stacked margin-base-bottom" do
      = label_tag :username
      = text_field_tag :username, '', class: '1/1'

      = label_tag :password
      = password_field_tag :password, '', class: '1/1'

      = label_tag do
        = check_box_tag :remember, params[:remember], true
        | Remember me

      div class="text-center"
        = submit_tag "Login now"

    ul class="list-reset"
      li= link_to "Don't have an account? Sign up!", new_user_path
      li= link_to "Start now without an account.", guests_path, method: :post